services:
  node-backend:
    build:
      context: ./resistbot-node-backend
    ports:
      - "5555:5555"
    environment:
      DISCORD_BOT_TOKEN: ${DISCORD_BOT_TOKEN}
      DISCORD_APP_ID: ${DISCORD_APP_ID}
      RP_NETLOC: ${RP_NETLOC}
      RP_BASEPATH: ${RP_BASEPATH}
      RP_SCHEME: ${RP_SCHEME}
  gateway-forwarder:
    build:
      context: ./resistbot-gateway-forwarder
    environment:
      DISCORD_BOT_TOKEN: ${DISCORD_BOT_TOKEN}
